#------------------------------------------------------
# Build and test node typescript app with node8
# on Ubuntu, VS2017 and Mac hosted VMs
#------------------------------------------------------
trigger:
- master
- features/*

jobs:
- job: 'Ubuntu_1604'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - template: azure-pipelines-steps.yml

- job: 'VS2017_Win2016'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - template: azure-pipelines-steps.yml

- job: 'MacOS_1013'
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - template: azure-pipelines-steps.yml
